#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_viki")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertAdminInfo(AdminInfo instance);
    partial void UpdateAdminInfo(AdminInfo instance);
    partial void DeleteAdminInfo(AdminInfo instance);
    partial void InsertBalanceInfo(BalanceInfo instance);
    partial void UpdateBalanceInfo(BalanceInfo instance);
    partial void DeleteBalanceInfo(BalanceInfo instance);
    partial void InsertBookInfo(BookInfo instance);
    partial void UpdateBookInfo(BookInfo instance);
    partial void DeleteBookInfo(BookInfo instance);
    partial void InsertClassRecordInfo(ClassRecordInfo instance);
    partial void UpdateClassRecordInfo(ClassRecordInfo instance);
    partial void DeleteClassRecordInfo(ClassRecordInfo instance);
    partial void InsertFeedbackInfo(FeedbackInfo instance);
    partial void UpdateFeedbackInfo(FeedbackInfo instance);
    partial void DeleteFeedbackInfo(FeedbackInfo instance);
    partial void InsertOrderRecordInfo(OrderRecordInfo instance);
    partial void UpdateOrderRecordInfo(OrderRecordInfo instance);
    partial void DeleteOrderRecordInfo(OrderRecordInfo instance);
    partial void InsertStudentInfo(StudentInfo instance);
    partial void UpdateStudentInfo(StudentInfo instance);
    partial void DeleteStudentInfo(StudentInfo instance);
    partial void InsertTeacherInfo(TeacherInfo instance);
    partial void UpdateTeacherInfo(TeacherInfo instance);
    partial void DeleteTeacherInfo(TeacherInfo instance);
    partial void InsertTestInfo(TestInfo instance);
    partial void UpdateTestInfo(TestInfo instance);
    partial void DeleteTestInfo(TestInfo instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::Model.Properties.Settings.Default.db_vikiConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AdminInfo> AdminInfo
		{
			get
			{
				return this.GetTable<AdminInfo>();
			}
		}
		
		public System.Data.Linq.Table<BalanceInfo> BalanceInfo
		{
			get
			{
				return this.GetTable<BalanceInfo>();
			}
		}
		
		public System.Data.Linq.Table<BookInfo> BookInfo
		{
			get
			{
				return this.GetTable<BookInfo>();
			}
		}
		
		public System.Data.Linq.Table<ClassRecordInfo> ClassRecordInfo
		{
			get
			{
				return this.GetTable<ClassRecordInfo>();
			}
		}
		
		public System.Data.Linq.Table<FeedbackInfo> FeedbackInfo
		{
			get
			{
				return this.GetTable<FeedbackInfo>();
			}
		}
		
		public System.Data.Linq.Table<OrderRecordInfo> OrderRecordInfo
		{
			get
			{
				return this.GetTable<OrderRecordInfo>();
			}
		}
		
		public System.Data.Linq.Table<StudentInfo> StudentInfo
		{
			get
			{
				return this.GetTable<StudentInfo>();
			}
		}
		
		public System.Data.Linq.Table<TeacherInfo> TeacherInfo
		{
			get
			{
				return this.GetTable<TeacherInfo>();
			}
		}
		
		public System.Data.Linq.Table<TestInfo> TestInfo
		{
			get
			{
				return this.GetTable<TestInfo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Admin")]
	public partial class AdminInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Adm_ID;
		
		private string _Adm_UserName;
		
		private string _Adm_Password;
		
		private string _Adm_Nickname;
		
		private System.Nullable<System.DateTime> _Adm_LastLogin;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAdm_IDChanging(int value);
    partial void OnAdm_IDChanged();
    partial void OnAdm_UserNameChanging(string value);
    partial void OnAdm_UserNameChanged();
    partial void OnAdm_PasswordChanging(string value);
    partial void OnAdm_PasswordChanged();
    partial void OnAdm_NicknameChanging(string value);
    partial void OnAdm_NicknameChanged();
    partial void OnAdm_LastLoginChanging(System.Nullable<System.DateTime> value);
    partial void OnAdm_LastLoginChanged();
    #endregion
		
		public AdminInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adm_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Adm_ID
		{
			get
			{
				return this._Adm_ID;
			}
			set
			{
				if ((this._Adm_ID != value))
				{
					this.OnAdm_IDChanging(value);
					this.SendPropertyChanging();
					this._Adm_ID = value;
					this.SendPropertyChanged("Adm_ID");
					this.OnAdm_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adm_UserName", DbType="VarChar(20)")]
		public string Adm_UserName
		{
			get
			{
				return this._Adm_UserName;
			}
			set
			{
				if ((this._Adm_UserName != value))
				{
					this.OnAdm_UserNameChanging(value);
					this.SendPropertyChanging();
					this._Adm_UserName = value;
					this.SendPropertyChanged("Adm_UserName");
					this.OnAdm_UserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adm_Password", DbType="VarChar(10)")]
		public string Adm_Password
		{
			get
			{
				return this._Adm_Password;
			}
			set
			{
				if ((this._Adm_Password != value))
				{
					this.OnAdm_PasswordChanging(value);
					this.SendPropertyChanging();
					this._Adm_Password = value;
					this.SendPropertyChanged("Adm_Password");
					this.OnAdm_PasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adm_Nickname", DbType="VarChar(20)")]
		public string Adm_Nickname
		{
			get
			{
				return this._Adm_Nickname;
			}
			set
			{
				if ((this._Adm_Nickname != value))
				{
					this.OnAdm_NicknameChanging(value);
					this.SendPropertyChanging();
					this._Adm_Nickname = value;
					this.SendPropertyChanged("Adm_Nickname");
					this.OnAdm_NicknameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adm_LastLogin", DbType="DateTime")]
		public System.Nullable<System.DateTime> Adm_LastLogin
		{
			get
			{
				return this._Adm_LastLogin;
			}
			set
			{
				if ((this._Adm_LastLogin != value))
				{
					this.OnAdm_LastLoginChanging(value);
					this.SendPropertyChanging();
					this._Adm_LastLogin = value;
					this.SendPropertyChanged("Adm_LastLogin");
					this.OnAdm_LastLoginChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Balance")]
	public partial class BalanceInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Bal_ID;
		
		private int _Stu_ID;
		
		private int _Tea_ID;
		
		private System.Nullable<System.DateTime> _Bal_Time;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBal_IDChanging(int value);
    partial void OnBal_IDChanged();
    partial void OnStu_IDChanging(int value);
    partial void OnStu_IDChanged();
    partial void OnTea_IDChanging(int value);
    partial void OnTea_IDChanged();
    partial void OnBal_TimeChanging(System.Nullable<System.DateTime> value);
    partial void OnBal_TimeChanged();
    #endregion
		
		public BalanceInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bal_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Bal_ID
		{
			get
			{
				return this._Bal_ID;
			}
			set
			{
				if ((this._Bal_ID != value))
				{
					this.OnBal_IDChanging(value);
					this.SendPropertyChanging();
					this._Bal_ID = value;
					this.SendPropertyChanged("Bal_ID");
					this.OnBal_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stu_ID", DbType="Int NOT NULL")]
		public int Stu_ID
		{
			get
			{
				return this._Stu_ID;
			}
			set
			{
				if ((this._Stu_ID != value))
				{
					this.OnStu_IDChanging(value);
					this.SendPropertyChanging();
					this._Stu_ID = value;
					this.SendPropertyChanged("Stu_ID");
					this.OnStu_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tea_ID", DbType="Int NOT NULL")]
		public int Tea_ID
		{
			get
			{
				return this._Tea_ID;
			}
			set
			{
				if ((this._Tea_ID != value))
				{
					this.OnTea_IDChanging(value);
					this.SendPropertyChanging();
					this._Tea_ID = value;
					this.SendPropertyChanged("Tea_ID");
					this.OnTea_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bal_Time", DbType="DateTime")]
		public System.Nullable<System.DateTime> Bal_Time
		{
			get
			{
				return this._Bal_Time;
			}
			set
			{
				if ((this._Bal_Time != value))
				{
					this.OnBal_TimeChanging(value);
					this.SendPropertyChanging();
					this._Bal_Time = value;
					this.SendPropertyChanged("Bal_Time");
					this.OnBal_TimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Book")]
	public partial class BookInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Boo_ID;
		
		private System.Nullable<int> _Tea_ID;
		
		private string _Boo_Image;
		
		private string _Boo_Desribe;
		
		private System.Nullable<System.DateTime> _Boo_RegisterDate;
		
		private string _Boo_Preview;
		
		private string _Boo_View;
		
		private string _Boo_Name;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBoo_IDChanging(int value);
    partial void OnBoo_IDChanged();
    partial void OnTea_IDChanging(System.Nullable<int> value);
    partial void OnTea_IDChanged();
    partial void OnBoo_ImageChanging(string value);
    partial void OnBoo_ImageChanged();
    partial void OnBoo_DesribeChanging(string value);
    partial void OnBoo_DesribeChanged();
    partial void OnBoo_RegisterDateChanging(System.Nullable<System.DateTime> value);
    partial void OnBoo_RegisterDateChanged();
    partial void OnBoo_PreviewChanging(string value);
    partial void OnBoo_PreviewChanged();
    partial void OnBoo_ViewChanging(string value);
    partial void OnBoo_ViewChanged();
    partial void OnBoo_NameChanging(string value);
    partial void OnBoo_NameChanged();
    #endregion
		
		public BookInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Boo_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Boo_ID
		{
			get
			{
				return this._Boo_ID;
			}
			set
			{
				if ((this._Boo_ID != value))
				{
					this.OnBoo_IDChanging(value);
					this.SendPropertyChanging();
					this._Boo_ID = value;
					this.SendPropertyChanged("Boo_ID");
					this.OnBoo_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tea_ID", DbType="Int")]
		public System.Nullable<int> Tea_ID
		{
			get
			{
				return this._Tea_ID;
			}
			set
			{
				if ((this._Tea_ID != value))
				{
					this.OnTea_IDChanging(value);
					this.SendPropertyChanging();
					this._Tea_ID = value;
					this.SendPropertyChanged("Tea_ID");
					this.OnTea_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Boo_Image", DbType="VarChar(50)")]
		public string Boo_Image
		{
			get
			{
				return this._Boo_Image;
			}
			set
			{
				if ((this._Boo_Image != value))
				{
					this.OnBoo_ImageChanging(value);
					this.SendPropertyChanging();
					this._Boo_Image = value;
					this.SendPropertyChanged("Boo_Image");
					this.OnBoo_ImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Boo_Desribe", DbType="VarChar(100)")]
		public string Boo_Desribe
		{
			get
			{
				return this._Boo_Desribe;
			}
			set
			{
				if ((this._Boo_Desribe != value))
				{
					this.OnBoo_DesribeChanging(value);
					this.SendPropertyChanging();
					this._Boo_Desribe = value;
					this.SendPropertyChanged("Boo_Desribe");
					this.OnBoo_DesribeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Boo_RegisterDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> Boo_RegisterDate
		{
			get
			{
				return this._Boo_RegisterDate;
			}
			set
			{
				if ((this._Boo_RegisterDate != value))
				{
					this.OnBoo_RegisterDateChanging(value);
					this.SendPropertyChanging();
					this._Boo_RegisterDate = value;
					this.SendPropertyChanged("Boo_RegisterDate");
					this.OnBoo_RegisterDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Boo_Preview", DbType="VarChar(50)")]
		public string Boo_Preview
		{
			get
			{
				return this._Boo_Preview;
			}
			set
			{
				if ((this._Boo_Preview != value))
				{
					this.OnBoo_PreviewChanging(value);
					this.SendPropertyChanging();
					this._Boo_Preview = value;
					this.SendPropertyChanged("Boo_Preview");
					this.OnBoo_PreviewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Boo_View", DbType="VarChar(50)")]
		public string Boo_View
		{
			get
			{
				return this._Boo_View;
			}
			set
			{
				if ((this._Boo_View != value))
				{
					this.OnBoo_ViewChanging(value);
					this.SendPropertyChanging();
					this._Boo_View = value;
					this.SendPropertyChanged("Boo_View");
					this.OnBoo_ViewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Boo_Name", DbType="VarChar(20)")]
		public string Boo_Name
		{
			get
			{
				return this._Boo_Name;
			}
			set
			{
				if ((this._Boo_Name != value))
				{
					this.OnBoo_NameChanging(value);
					this.SendPropertyChanging();
					this._Boo_Name = value;
					this.SendPropertyChanged("Boo_Name");
					this.OnBoo_NameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_ClassRecord")]
	public partial class ClassRecordInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Cla_ID;
		
		private System.Nullable<int> _Stu_ID;
		
		private System.Nullable<int> _Tea_ID;
		
		private System.Nullable<System.DateTime> _Cla_StartTime;
		
		private System.Nullable<System.DateTime> _Cla_EndTime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCla_IDChanging(int value);
    partial void OnCla_IDChanged();
    partial void OnStu_IDChanging(System.Nullable<int> value);
    partial void OnStu_IDChanged();
    partial void OnTea_IDChanging(System.Nullable<int> value);
    partial void OnTea_IDChanged();
    partial void OnCla_StartTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCla_StartTimeChanged();
    partial void OnCla_EndTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCla_EndTimeChanged();
    #endregion
		
		public ClassRecordInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cla_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Cla_ID
		{
			get
			{
				return this._Cla_ID;
			}
			set
			{
				if ((this._Cla_ID != value))
				{
					this.OnCla_IDChanging(value);
					this.SendPropertyChanging();
					this._Cla_ID = value;
					this.SendPropertyChanged("Cla_ID");
					this.OnCla_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stu_ID", DbType="Int")]
		public System.Nullable<int> Stu_ID
		{
			get
			{
				return this._Stu_ID;
			}
			set
			{
				if ((this._Stu_ID != value))
				{
					this.OnStu_IDChanging(value);
					this.SendPropertyChanging();
					this._Stu_ID = value;
					this.SendPropertyChanged("Stu_ID");
					this.OnStu_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tea_ID", DbType="Int")]
		public System.Nullable<int> Tea_ID
		{
			get
			{
				return this._Tea_ID;
			}
			set
			{
				if ((this._Tea_ID != value))
				{
					this.OnTea_IDChanging(value);
					this.SendPropertyChanging();
					this._Tea_ID = value;
					this.SendPropertyChanged("Tea_ID");
					this.OnTea_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cla_StartTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> Cla_StartTime
		{
			get
			{
				return this._Cla_StartTime;
			}
			set
			{
				if ((this._Cla_StartTime != value))
				{
					this.OnCla_StartTimeChanging(value);
					this.SendPropertyChanging();
					this._Cla_StartTime = value;
					this.SendPropertyChanged("Cla_StartTime");
					this.OnCla_StartTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cla_EndTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> Cla_EndTime
		{
			get
			{
				return this._Cla_EndTime;
			}
			set
			{
				if ((this._Cla_EndTime != value))
				{
					this.OnCla_EndTimeChanging(value);
					this.SendPropertyChanging();
					this._Cla_EndTime = value;
					this.SendPropertyChanged("Cla_EndTime");
					this.OnCla_EndTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Feedback")]
	public partial class FeedbackInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Fee_ID;
		
		private System.Nullable<int> _Stu_ID;
		
		private string _Fee_Topic;
		
		private string _Fee_Detail;
		
		private System.Nullable<System.DateTime> _Fee_Time;
		
		private System.Nullable<char> _Fee_Level;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFee_IDChanging(int value);
    partial void OnFee_IDChanged();
    partial void OnStu_IDChanging(System.Nullable<int> value);
    partial void OnStu_IDChanged();
    partial void OnFee_TopicChanging(string value);
    partial void OnFee_TopicChanged();
    partial void OnFee_DetailChanging(string value);
    partial void OnFee_DetailChanged();
    partial void OnFee_TimeChanging(System.Nullable<System.DateTime> value);
    partial void OnFee_TimeChanged();
    partial void OnFee_LevelChanging(System.Nullable<char> value);
    partial void OnFee_LevelChanged();
    #endregion
		
		public FeedbackInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Fee_ID
		{
			get
			{
				return this._Fee_ID;
			}
			set
			{
				if ((this._Fee_ID != value))
				{
					this.OnFee_IDChanging(value);
					this.SendPropertyChanging();
					this._Fee_ID = value;
					this.SendPropertyChanged("Fee_ID");
					this.OnFee_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stu_ID", DbType="Int")]
		public System.Nullable<int> Stu_ID
		{
			get
			{
				return this._Stu_ID;
			}
			set
			{
				if ((this._Stu_ID != value))
				{
					this.OnStu_IDChanging(value);
					this.SendPropertyChanging();
					this._Stu_ID = value;
					this.SendPropertyChanged("Stu_ID");
					this.OnStu_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee_Topic", DbType="VarChar(50)")]
		public string Fee_Topic
		{
			get
			{
				return this._Fee_Topic;
			}
			set
			{
				if ((this._Fee_Topic != value))
				{
					this.OnFee_TopicChanging(value);
					this.SendPropertyChanging();
					this._Fee_Topic = value;
					this.SendPropertyChanged("Fee_Topic");
					this.OnFee_TopicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee_Detail", DbType="VarChar(100)")]
		public string Fee_Detail
		{
			get
			{
				return this._Fee_Detail;
			}
			set
			{
				if ((this._Fee_Detail != value))
				{
					this.OnFee_DetailChanging(value);
					this.SendPropertyChanging();
					this._Fee_Detail = value;
					this.SendPropertyChanged("Fee_Detail");
					this.OnFee_DetailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee_Time", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fee_Time
		{
			get
			{
				return this._Fee_Time;
			}
			set
			{
				if ((this._Fee_Time != value))
				{
					this.OnFee_TimeChanging(value);
					this.SendPropertyChanging();
					this._Fee_Time = value;
					this.SendPropertyChanged("Fee_Time");
					this.OnFee_TimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fee_Level", DbType="Char(1)")]
		public System.Nullable<char> Fee_Level
		{
			get
			{
				return this._Fee_Level;
			}
			set
			{
				if ((this._Fee_Level != value))
				{
					this.OnFee_LevelChanging(value);
					this.SendPropertyChanging();
					this._Fee_Level = value;
					this.SendPropertyChanged("Fee_Level");
					this.OnFee_LevelChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_OrderRecord")]
	public partial class OrderRecordInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ord_ID;
		
		private System.Nullable<int> _Stu_ID;
		
		private System.Nullable<int> _Tea_ID;
		
		private System.Nullable<System.DateTime> _Ord_Time;
		
		private System.Nullable<int> _Ord_Plan;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOrd_IDChanging(int value);
    partial void OnOrd_IDChanged();
    partial void OnStu_IDChanging(System.Nullable<int> value);
    partial void OnStu_IDChanged();
    partial void OnTea_IDChanging(System.Nullable<int> value);
    partial void OnTea_IDChanged();
    partial void OnOrd_TimeChanging(System.Nullable<System.DateTime> value);
    partial void OnOrd_TimeChanged();
    partial void OnOrd_PlanChanging(System.Nullable<int> value);
    partial void OnOrd_PlanChanged();
    #endregion
		
		public OrderRecordInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ord_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Ord_ID
		{
			get
			{
				return this._Ord_ID;
			}
			set
			{
				if ((this._Ord_ID != value))
				{
					this.OnOrd_IDChanging(value);
					this.SendPropertyChanging();
					this._Ord_ID = value;
					this.SendPropertyChanged("Ord_ID");
					this.OnOrd_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stu_ID", DbType="Int")]
		public System.Nullable<int> Stu_ID
		{
			get
			{
				return this._Stu_ID;
			}
			set
			{
				if ((this._Stu_ID != value))
				{
					this.OnStu_IDChanging(value);
					this.SendPropertyChanging();
					this._Stu_ID = value;
					this.SendPropertyChanged("Stu_ID");
					this.OnStu_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tea_ID", DbType="Int")]
		public System.Nullable<int> Tea_ID
		{
			get
			{
				return this._Tea_ID;
			}
			set
			{
				if ((this._Tea_ID != value))
				{
					this.OnTea_IDChanging(value);
					this.SendPropertyChanging();
					this._Tea_ID = value;
					this.SendPropertyChanged("Tea_ID");
					this.OnTea_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ord_Time", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ord_Time
		{
			get
			{
				return this._Ord_Time;
			}
			set
			{
				if ((this._Ord_Time != value))
				{
					this.OnOrd_TimeChanging(value);
					this.SendPropertyChanging();
					this._Ord_Time = value;
					this.SendPropertyChanged("Ord_Time");
					this.OnOrd_TimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ord_Plan", DbType="Int")]
		public System.Nullable<int> Ord_Plan
		{
			get
			{
				return this._Ord_Plan;
			}
			set
			{
				if ((this._Ord_Plan != value))
				{
					this.OnOrd_PlanChanging(value);
					this.SendPropertyChanging();
					this._Ord_Plan = value;
					this.SendPropertyChanged("Ord_Plan");
					this.OnOrd_PlanChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Student")]
	public partial class StudentInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Stu_ID;
		
		private string _Stu_UserName;
		
		private string _Stu_Password;
		
		private string _Stu_Email;
		
		private string _Stu_Image;
		
		private System.Nullable<System.DateTime> _Stu_LastLogin;
		
		private System.Nullable<System.DateTime> _Stu_RegisteTime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStu_IDChanging(int value);
    partial void OnStu_IDChanged();
    partial void OnStu_UserNameChanging(string value);
    partial void OnStu_UserNameChanged();
    partial void OnStu_PasswordChanging(string value);
    partial void OnStu_PasswordChanged();
    partial void OnStu_EmailChanging(string value);
    partial void OnStu_EmailChanged();
    partial void OnStu_ImageChanging(string value);
    partial void OnStu_ImageChanged();
    partial void OnStu_LastLoginChanging(System.Nullable<System.DateTime> value);
    partial void OnStu_LastLoginChanged();
    partial void OnStu_RegisteTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnStu_RegisteTimeChanged();
    #endregion
		
		public StudentInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stu_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Stu_ID
		{
			get
			{
				return this._Stu_ID;
			}
			set
			{
				if ((this._Stu_ID != value))
				{
					this.OnStu_IDChanging(value);
					this.SendPropertyChanging();
					this._Stu_ID = value;
					this.SendPropertyChanged("Stu_ID");
					this.OnStu_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stu_UserName", DbType="VarChar(10)")]
		public string Stu_UserName
		{
			get
			{
				return this._Stu_UserName;
			}
			set
			{
				if ((this._Stu_UserName != value))
				{
					this.OnStu_UserNameChanging(value);
					this.SendPropertyChanging();
					this._Stu_UserName = value;
					this.SendPropertyChanged("Stu_UserName");
					this.OnStu_UserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stu_Password", DbType="VarChar(10)")]
		public string Stu_Password
		{
			get
			{
				return this._Stu_Password;
			}
			set
			{
				if ((this._Stu_Password != value))
				{
					this.OnStu_PasswordChanging(value);
					this.SendPropertyChanging();
					this._Stu_Password = value;
					this.SendPropertyChanged("Stu_Password");
					this.OnStu_PasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stu_Email", DbType="VarChar(20)")]
		public string Stu_Email
		{
			get
			{
				return this._Stu_Email;
			}
			set
			{
				if ((this._Stu_Email != value))
				{
					this.OnStu_EmailChanging(value);
					this.SendPropertyChanging();
					this._Stu_Email = value;
					this.SendPropertyChanged("Stu_Email");
					this.OnStu_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stu_Image", DbType="VarChar(50)")]
		public string Stu_Image
		{
			get
			{
				return this._Stu_Image;
			}
			set
			{
				if ((this._Stu_Image != value))
				{
					this.OnStu_ImageChanging(value);
					this.SendPropertyChanging();
					this._Stu_Image = value;
					this.SendPropertyChanged("Stu_Image");
					this.OnStu_ImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stu_LastLogin", DbType="DateTime")]
		public System.Nullable<System.DateTime> Stu_LastLogin
		{
			get
			{
				return this._Stu_LastLogin;
			}
			set
			{
				if ((this._Stu_LastLogin != value))
				{
					this.OnStu_LastLoginChanging(value);
					this.SendPropertyChanging();
					this._Stu_LastLogin = value;
					this.SendPropertyChanged("Stu_LastLogin");
					this.OnStu_LastLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stu_RegisteTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> Stu_RegisteTime
		{
			get
			{
				return this._Stu_RegisteTime;
			}
			set
			{
				if ((this._Stu_RegisteTime != value))
				{
					this.OnStu_RegisteTimeChanging(value);
					this.SendPropertyChanging();
					this._Stu_RegisteTime = value;
					this.SendPropertyChanged("Stu_RegisteTime");
					this.OnStu_RegisteTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Teacher")]
	public partial class TeacherInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Tea_ID;
		
		private string _Tea_Name;
		
		private string _Tea_Nickname;
		
		private string _Tea_Image;
		
		private string _Tea_Describe;
		
		private string _Tea_Sex;
		
		private System.Nullable<int> _Tea_Age;
		
		private string _Tea_Skill;
		
		private string _Tea_Nation;
		
		private string _Tea_About;
		
		private string _Tea_Suitable;
		
		private string _Tea_SImage;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTea_IDChanging(int value);
    partial void OnTea_IDChanged();
    partial void OnTea_NameChanging(string value);
    partial void OnTea_NameChanged();
    partial void OnTea_NicknameChanging(string value);
    partial void OnTea_NicknameChanged();
    partial void OnTea_ImageChanging(string value);
    partial void OnTea_ImageChanged();
    partial void OnTea_DescribeChanging(string value);
    partial void OnTea_DescribeChanged();
    partial void OnTea_SexChanging(string value);
    partial void OnTea_SexChanged();
    partial void OnTea_AgeChanging(System.Nullable<int> value);
    partial void OnTea_AgeChanged();
    partial void OnTea_SkillChanging(string value);
    partial void OnTea_SkillChanged();
    partial void OnTea_NationChanging(string value);
    partial void OnTea_NationChanged();
    partial void OnTea_AboutChanging(string value);
    partial void OnTea_AboutChanged();
    partial void OnTea_SuitableChanging(string value);
    partial void OnTea_SuitableChanged();
    partial void OnTea_SImageChanging(string value);
    partial void OnTea_SImageChanged();
    #endregion
		
		public TeacherInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tea_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Tea_ID
		{
			get
			{
				return this._Tea_ID;
			}
			set
			{
				if ((this._Tea_ID != value))
				{
					this.OnTea_IDChanging(value);
					this.SendPropertyChanging();
					this._Tea_ID = value;
					this.SendPropertyChanged("Tea_ID");
					this.OnTea_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tea_Name", DbType="VarChar(20)")]
		public string Tea_Name
		{
			get
			{
				return this._Tea_Name;
			}
			set
			{
				if ((this._Tea_Name != value))
				{
					this.OnTea_NameChanging(value);
					this.SendPropertyChanging();
					this._Tea_Name = value;
					this.SendPropertyChanged("Tea_Name");
					this.OnTea_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tea_Nickname", DbType="VarChar(20)")]
		public string Tea_Nickname
		{
			get
			{
				return this._Tea_Nickname;
			}
			set
			{
				if ((this._Tea_Nickname != value))
				{
					this.OnTea_NicknameChanging(value);
					this.SendPropertyChanging();
					this._Tea_Nickname = value;
					this.SendPropertyChanged("Tea_Nickname");
					this.OnTea_NicknameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tea_Image", DbType="VarChar(50)")]
		public string Tea_Image
		{
			get
			{
				return this._Tea_Image;
			}
			set
			{
				if ((this._Tea_Image != value))
				{
					this.OnTea_ImageChanging(value);
					this.SendPropertyChanging();
					this._Tea_Image = value;
					this.SendPropertyChanged("Tea_Image");
					this.OnTea_ImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tea_Describe", DbType="VarChar(MAX)")]
		public string Tea_Describe
		{
			get
			{
				return this._Tea_Describe;
			}
			set
			{
				if ((this._Tea_Describe != value))
				{
					this.OnTea_DescribeChanging(value);
					this.SendPropertyChanging();
					this._Tea_Describe = value;
					this.SendPropertyChanged("Tea_Describe");
					this.OnTea_DescribeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tea_Sex", DbType="Char(10)")]
		public string Tea_Sex
		{
			get
			{
				return this._Tea_Sex;
			}
			set
			{
				if ((this._Tea_Sex != value))
				{
					this.OnTea_SexChanging(value);
					this.SendPropertyChanging();
					this._Tea_Sex = value;
					this.SendPropertyChanged("Tea_Sex");
					this.OnTea_SexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tea_Age", DbType="Int")]
		public System.Nullable<int> Tea_Age
		{
			get
			{
				return this._Tea_Age;
			}
			set
			{
				if ((this._Tea_Age != value))
				{
					this.OnTea_AgeChanging(value);
					this.SendPropertyChanging();
					this._Tea_Age = value;
					this.SendPropertyChanged("Tea_Age");
					this.OnTea_AgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tea_Skill", DbType="VarChar(50)")]
		public string Tea_Skill
		{
			get
			{
				return this._Tea_Skill;
			}
			set
			{
				if ((this._Tea_Skill != value))
				{
					this.OnTea_SkillChanging(value);
					this.SendPropertyChanging();
					this._Tea_Skill = value;
					this.SendPropertyChanged("Tea_Skill");
					this.OnTea_SkillChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tea_Nation", DbType="VarChar(20)")]
		public string Tea_Nation
		{
			get
			{
				return this._Tea_Nation;
			}
			set
			{
				if ((this._Tea_Nation != value))
				{
					this.OnTea_NationChanging(value);
					this.SendPropertyChanging();
					this._Tea_Nation = value;
					this.SendPropertyChanged("Tea_Nation");
					this.OnTea_NationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tea_About", DbType="VarChar(100)")]
		public string Tea_About
		{
			get
			{
				return this._Tea_About;
			}
			set
			{
				if ((this._Tea_About != value))
				{
					this.OnTea_AboutChanging(value);
					this.SendPropertyChanging();
					this._Tea_About = value;
					this.SendPropertyChanged("Tea_About");
					this.OnTea_AboutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tea_Suitable", DbType="VarChar(100)")]
		public string Tea_Suitable
		{
			get
			{
				return this._Tea_Suitable;
			}
			set
			{
				if ((this._Tea_Suitable != value))
				{
					this.OnTea_SuitableChanging(value);
					this.SendPropertyChanging();
					this._Tea_Suitable = value;
					this.SendPropertyChanged("Tea_Suitable");
					this.OnTea_SuitableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tea_SImage", DbType="VarChar(50)")]
		public string Tea_SImage
		{
			get
			{
				return this._Tea_SImage;
			}
			set
			{
				if ((this._Tea_SImage != value))
				{
					this.OnTea_SImageChanging(value);
					this.SendPropertyChanging();
					this._Tea_SImage = value;
					this.SendPropertyChanged("Tea_SImage");
					this.OnTea_SImageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Test")]
	public partial class TestInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Tes_ID;
		
		private string _Tes_Type;
		
		private string _Tes_Detail;
		
		private string _Tes_A;
		
		private string _Tes_B;
		
		private string _Tes_C;
		
		private string _Tes_D;
		
		private System.Nullable<int> _Tes_Answer;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTes_IDChanging(int value);
    partial void OnTes_IDChanged();
    partial void OnTes_TypeChanging(string value);
    partial void OnTes_TypeChanged();
    partial void OnTes_DetailChanging(string value);
    partial void OnTes_DetailChanged();
    partial void OnTes_AChanging(string value);
    partial void OnTes_AChanged();
    partial void OnTes_BChanging(string value);
    partial void OnTes_BChanged();
    partial void OnTes_CChanging(string value);
    partial void OnTes_CChanged();
    partial void OnTes_DChanging(string value);
    partial void OnTes_DChanged();
    partial void OnTes_AnswerChanging(System.Nullable<int> value);
    partial void OnTes_AnswerChanged();
    #endregion
		
		public TestInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tes_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Tes_ID
		{
			get
			{
				return this._Tes_ID;
			}
			set
			{
				if ((this._Tes_ID != value))
				{
					this.OnTes_IDChanging(value);
					this.SendPropertyChanging();
					this._Tes_ID = value;
					this.SendPropertyChanged("Tes_ID");
					this.OnTes_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tes_Type", DbType="VarChar(20)")]
		public string Tes_Type
		{
			get
			{
				return this._Tes_Type;
			}
			set
			{
				if ((this._Tes_Type != value))
				{
					this.OnTes_TypeChanging(value);
					this.SendPropertyChanging();
					this._Tes_Type = value;
					this.SendPropertyChanged("Tes_Type");
					this.OnTes_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tes_Detail", DbType="VarChar(100)")]
		public string Tes_Detail
		{
			get
			{
				return this._Tes_Detail;
			}
			set
			{
				if ((this._Tes_Detail != value))
				{
					this.OnTes_DetailChanging(value);
					this.SendPropertyChanging();
					this._Tes_Detail = value;
					this.SendPropertyChanged("Tes_Detail");
					this.OnTes_DetailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tes_A", DbType="VarChar(20)")]
		public string Tes_A
		{
			get
			{
				return this._Tes_A;
			}
			set
			{
				if ((this._Tes_A != value))
				{
					this.OnTes_AChanging(value);
					this.SendPropertyChanging();
					this._Tes_A = value;
					this.SendPropertyChanged("Tes_A");
					this.OnTes_AChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tes_B", DbType="VarChar(20)")]
		public string Tes_B
		{
			get
			{
				return this._Tes_B;
			}
			set
			{
				if ((this._Tes_B != value))
				{
					this.OnTes_BChanging(value);
					this.SendPropertyChanging();
					this._Tes_B = value;
					this.SendPropertyChanged("Tes_B");
					this.OnTes_BChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tes_C", DbType="VarChar(20)")]
		public string Tes_C
		{
			get
			{
				return this._Tes_C;
			}
			set
			{
				if ((this._Tes_C != value))
				{
					this.OnTes_CChanging(value);
					this.SendPropertyChanging();
					this._Tes_C = value;
					this.SendPropertyChanged("Tes_C");
					this.OnTes_CChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tes_D", DbType="VarChar(20)")]
		public string Tes_D
		{
			get
			{
				return this._Tes_D;
			}
			set
			{
				if ((this._Tes_D != value))
				{
					this.OnTes_DChanging(value);
					this.SendPropertyChanging();
					this._Tes_D = value;
					this.SendPropertyChanged("Tes_D");
					this.OnTes_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tes_Answer", DbType="Int")]
		public System.Nullable<int> Tes_Answer
		{
			get
			{
				return this._Tes_Answer;
			}
			set
			{
				if ((this._Tes_Answer != value))
				{
					this.OnTes_AnswerChanging(value);
					this.SendPropertyChanging();
					this._Tes_Answer = value;
					this.SendPropertyChanged("Tes_Answer");
					this.OnTes_AnswerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
